server:
  port: 8083

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: techprocess-service
          uri: lb://techprocess-service
          predicates:
            - Path=/api/v1/techprocess-service, /api/v1/techprocess-service/**
          filters:
            - TokenRelay

        - id: library-equipments
          uri: lb://technical-library-service
          predicates:
            - Path=/api/v1/library-service/equipments, /api/v1/library-service/equipments/**
          filters:
            - TokenRelay

        - id: library-materials
          uri: lb://technical-library-service
          predicates:
            - Path=/api/v1/library-service/materials, /api/v1/library-service/materials/**
          filters:
            - TokenRelay

        - id: library-safety-instructions
          uri: lb://technical-library-service
          predicates:
            - Path=/api/v1/library-service/safety-instructions, /api/v1/library-service/safety-instructions/**
          filters:
            - TokenRelay

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification-service, /api/v1/notification-service/**
          filters:
            - TokenRelay

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus,metrics,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.cloud: INFO
