server:
  port: 8084

logging:
  level:
    root: INFO

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${NOTIFICATION_DB_URL}
    username: ${NOTIFICATION_DB_USERNAME}
    password: ${NOTIFICATION_DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: notification_service
        
  kafka:
    consumer:
      properties:
        spring.json.type.mapping: |
          by.niruin.library.model.event.material.MaterialCreatedEvent:by.niruin.notification_service.model.event.technical_library.material.MaterialCreatedEvent,
          by.niruin.library.model.event.material.MaterialUpdatedEvent:by.niruin.notification_service.model.event.technical_library.material.MaterialUpdatedEvent,
          by.niruin.library.model.event.material.MaterialDeletedEvent:by.niruin.notification_service.model.event.technical_library.material.MaterialDeletedEvent,
          by.niruin.library.model.event.equipment.EquipmentCreatedEvent:by.niruin.notification_service.model.event.technical_library.equipment.EquipmentCreatedEvent,
          by.niruin.library.model.event.equipment.EquipmentUpdatedEvent:by.niruin.notification_service.model.event.technical_library.equipment.EquipmentUpdatedEvent,
          by.niruin.library.model.event.equipment.EquipmentDeletedEvent:by.niruin.notification_service.model.event.technical_library.equipment.EquipmentDeletedEvent,
          by.niruin.library.model.event.instruction.SafetyInstructionCreatedEvent:by.niruin.notification_service.model.event.technical_library.safety_instruction.SafetyInstructionCreatedEvent,
          by.niruin.library.model.event.instruction.SafetyInstructionUpdatedEvent:by.niruin.notification_service.model.event.technical_library.safety_instruction.SafetyInstructionUpdatedEvent,
          by.niruin.library.model.event.instruction.SafetyInstructionDeletedEvent:by.niruin.notification_service.model.event.technical_library.safety_instruction.SafetyInstructionDeletedEvent,
          by.niruin.techprocess_service.model.event.technological_process.TechnologicalProcessCreatedEvent:by.niruin.notification_service.model.event.technological_process.TechnologicalProcessCreatedEvent,
          by.niruin.techprocess_service.model.event.technological_process.TechnologicalProcessUpdatedEvent:by.niruin.notification_service.model.event.technological_process.TechnologicalProcessUpdatedEvent,
          by.niruin.techprocess_service.model.event.technological_process.TechnologicalProcessApprovedEvent:by.niruin.notification_service.model.event.technological_process.TechnologicalProcessApprovedEvent,
          by.niruin.techprocess_service.model.event.technological_process.TechnologicalProcessCancelledEvent:by.niruin.notification_service.model.event.technological_process.TechnologicalProcessCancelledEvent,
          by.niruin.techprocess_service.model.event.technological_process.TechnologicalProcessReturnedAfterReviewEvent:by.niruin.notification_service.model.event.technological_process.TechnologicalProcessReturnedAfterReviewEvent,
          by.niruin.techprocess_service.model.event.technological_process.TechnologicalProcessSentToReviewEvent:by.niruin.notification_service.model.event.technological_process.TechnologicalProcessSentToReviewEvent

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: notification-service
