server:
  port: 8082

logging:
  level:
    root: INFO

scheduler:
  outbox:
    batch-size: 10
    millis-delay: 5000

file-service:
  url: ${FILE_SERVICE_URL}
  path: /api/v1/file-service/files/images

spring:
  mongodb:
    uri: ${MONGODB_URI}

  data:
    mongodb:
      uri: ${MONGODB_URI}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.trusted.packages: '*'

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: techprocess-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
        register-health-indicator: true
    instances:
      techprocessService:
        baseConfig: default

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.net.SocketTimeoutException
    instances:
      techprocessService:
        baseConfig: default